<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron mb-0 secondary-color">
    <h1 class="container display-4">Join Us</h1>
</div>

<div class="container pt-5">
    <p class="lead">To join, you need to fill out one of the forms below.</p>
    <p class="lead">
        If you would like to talk to someone before filling out the form,
        please contact the membership secretary by email at <a href="mailto:membership@tatasteelsailing.org.uk">membership@tatasteelsailing.org.uk</a>.
    </p>
    <hr>
</div>

<div class="container pt-5">
    <div class="row text-center">
        <!-- membership application -->
        <div class="col-lg-4 col-sm-12 pb-5">
            <a href="<?= $this->url('join/membership') ?>">
                <h3 class="page-header pb-3 mb-3">Membership <i class="fa fa-link"></i></h3>
            </a>
            <p class="lead">
                Anyone can apply to be a member of this club, only limited by your own abilities.
                We offer storage space for two craft as well as various help and advice as part of your membership fees, with additional spaces available at an extra charge depending on availability.
                Training is available and is carried out to RYA standards (See the <a href="<?= $this->url('training') ?>" >Training Page</a> for information on training).
            </p>
        </div>

        <!-- group membership application -->
        <div class="col-lg-4 col-sm-12 pb-5">
            <a href="<?= $this->url('join/group') ?>">
                <h3 class="page-header pb-3 mb-3">Group Membership <i class="fa fa-link"></i></h3>
            </a>
            <p class="lead">
                This form is to be used by an Organisation wanting to apply for a group membership.
                A separate form is to be submitted for each payee.
                Each payee will be invoiced separately; One application for each invoice and each subsequent payment.
            </p>
        </div>

        <!-- open series application -->
        <div class="col-lg-4 col-sm-12 pb-5">
            <a href="<?= $this->url('join/open') ?>">
                <h3 class="page-header pb-3 mb-3">Open Series <i class="fa fa-link"></i></h3>
            </a>
            <p class="lead">
                Autumn and Winter Series' have been opened up for guest participation.
                Please use this form to apply, one form per Series. An application recieved will assumed to be for the current series.
                If you are applying for a future series, then follow the application form up with an email to the membership secretary.
                We offer storage space for two craft as well as full accesss to our facilities.
            </p>
        </div>
    </div>
</div>