<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron secondary-color">
    <h1 class="container display-4">Our Team</h1>
</div>

<div class="container-fluid p-5">
    <div class="container mx-auto">

        <!-- flag officers -->
        <h2 class="page-header pb-3 mb-5 text-center">Flag Officers</h2>
        <div class="row justify-content-center">

            <!-- Linda - Commodore -->
            <div class="col-lg-4">
                <div class="our-team-main">
                    <img src="<?= $this->basePath('/img/facebank/LindaIngram.jpg') ?>" class="img-small img-fluid" />
                    <h3>Linda Ingram</h3>
                    <p>Commodore</p>
                </div>
            </div>

            <!-- John - Vice-Commodore, Results Officer, Webmaster -->
            <div class="col-lg-4">
                <div class="our-team-main">
                    <img src="<?= $this->basePath('/img/facebank/JohnRischmiller.jpg') ?>" class="img-small img-fluid" />
                    <h3>John Rischmiller</h3>
                    <p>Vice-Commodore</p>
                </div>
            </div>

            <!-- Stan - Rear Commodore -->
            <div class="col-lg-4">
                <div class="our-team-main">
                    <img src="<?= $this->basePath('/img/facebank/StanWilliams.jpg') ?>" class="img-small img-fluid" />
                    <h3>Stan Williams</h3>
                    <p>Rear Commodore</p>
                </div>
            </div>

            <!-- Glen - Hon Treasurer -->
            <div class="col-lg-4">
                <div class="our-team-main">
                    <img src="<?= $this->basePath('/img/facebank/GlenWilbraham.jpg') ?>" class="img-small img-fluid" />
                    <h3>Hon Treasurer</h3>
                    <p>Glen Wilbraham</p>
                </div>
            </div>

        </div>

        <!-- Management Committee -->
        <h2 class="page-header pb-3 pt-5 mb-5 m-3 text-center">Managment Committee</h2>
        <div class="row justify-content-center">

            <!-- Jeremy - Training Centre Principal -->
            <div class="col-lg-4">
                <div class="our-team-main">
                    <img src="<?= $this->basePath('/img/facebank/JeremyMartin.jpg') ?>" class="img-small img-fluid" />
                    <h3>Jeremy Martin</h3>
                    <p>Training Centre Principal</p>
                </div>
            </div>

            <!-- Paul - Membership Secretary-->
            <div class="col-lg-4">
                <div class="our-team-main">
                    <img src="<?= $this->basePath('/img/facebank/PaulBambridge.jpg') ?>" class="img-small img-fluid" />
                    <h3>Paul Bambridge</h3>
                    <p>Membership Secretary</p>
                </div>
            </div>

            <!-- Ruth - Young Persons Welfare Officer -->
            <div class="col-lg-4">
                <div class="our-team-main">
                    <img src="<?= $this->basePath('/img/facebank/RuthEvans.jpg') ?>" class="img-small img-fluid" />
                    <h3>Ruth Evans</h3>
                    <p>Young Persons Welfare Officer</p>
                </div>
            </div>

            <!-- Alan - Windsurfing Rep-->
            <div class="col-lg-4">
                <div class="our-team-main">
                    <img src="<?= $this->basePath('/img/facebank/AlanBreeze.jpg') ?>" class="img-small img-fluid" />
                    <h3>Alan Breeze</h3>
                    <p>Windsurfing Rep</p>
                </div>
            </div>

            <!-- Karen - Committee Member -->
            <div class="col-lg-4">
                <div class="our-team-main">
                    <img src="<?= $this->basePath('/img/facebank/Placeholder.png') ?>" class="img-small img-fluid" />
                    <h3>Karen Burch</h3>
                    <p>Committee Member</p>
                </div>
            </div>

            <!-- Dave - Committee Member-->
            <div class="col-lg-4">
                <div class="our-team-main">
                    <img src="<?= $this->basePath('/img/facebank/Placeholder.png') ?>" class="img-small img-fluid" />
                    <h3>Dave Burch</h3>
                    <p>Committee Member</p>
                </div>
            </div>

            <!-- Stan - Publicity Officer -->
            <div class="col-lg-4">
                <div class="our-team-main">
                    <img src="<?= $this->basePath('/img/facebank/StanWilliams.jpg') ?>" class="img-small img-fluid" />
                    <h3>Stan Williams</h3>
                    <p>Publicity Officer</p>
                </div>
            </div>

            <!-- Pat - Committee Member -->
            <div class="col-lg-4">
                <div class="our-team-main">
                    <img src="<?= $this->basePath('/img/facebank/PatMoore.jpg') ?>" class="img-small img-fluid" />
                    <h3>Pat Moore</h3>
                    <p>Committee Member</p>
                </div>
            </div>

            <!-- Paul - Solo Fleet Captain-->
            <div class="col-lg-4">
                <div class="our-team-main">
                    <img src="<?= $this->basePath('/img/facebank/PaulBambridge.jpg') ?>" class="img-small img-fluid" />
                    <h3>Paul Bambridge</h3>
                    <p>Solo Fleet Captain</p>
                </div>
            </div>

            <!-- Paul - Bosun -->
            <div class="col-lg-4">
                <div class="our-team-main">
                    <img src="<?= $this->basePath('/img/facebank/PaulGovier.jpg') ?>" class="img-small img-fluid" />
                    <h3>Pauk Govier</h3>
                    <p>Bosun</p>
                </div>
            </div>

        </div>

         <!-- Management Committee -->
        <h2 class="page-header pb-3 pt-5 mb-5 m-3 text-center">Non-committee Roles</h2>
        <div class="row justify-content-center">

            <!-- David - Compound Manager -->
            <div class="col-lg-4">
                <div class="our-team-main">
                    <img src="<?= $this->basePath('/img/facebank/DavidTozer.jpg') ?>" class="img-small img-fluid" />
                    <h3>David Tozer</h3>
                    <p>Compound Manager</p>
                </div>
            </div>

            <!-- Alan - Traning Liaison Officer -->
            <div class="col-lg-4">
                <div class="our-team-main">
                        <img src="<?= $this->basePath('/img/facebank/AlanBreeze.jpg') ?>" class="img-small img-fluid" />
                        <h3>Alan Breeze</h3>
                        <p>Training Liaison Offiver</p>
                    </div>
            </div>

            <!-- John - Webmaster -->
            <div class="col-lg-4">
                <div class="our-team-main">
                <img src="<?= $this->basePath('/img/facebank/JohnRischmiller.jpg') ?>" class="img-small img-fluid" />
                <h3>John Rischmiller</h3>
                <p>Webmaster</p>
            </div>
        </div>
    </div>
</div>