<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron secondary-color">
    <h1 class="container display-4">Our Team</h1>
</div>

<div class="container-fluid p-5">
    <div class="container">
            <div class="row">

                <!-- team-1 -->
                <div class="col-lg-4">
                    <div class="our-team-main">
                        <div class="team-front">
                            <img src="http://placehold.it/110x110/9c27b0/fff?text=Webmaster" class="img-fluid" />
                            <h3>Dilip Kevat</h3>
                            <p>Web Designer</p>
                        </div>
                        <div class="team-back">
                            <span>
                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis 
                                natoque penatibus et magnis dis parturient montes,
                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis 
                                natoque.
                            </span>
                        </div>
                    </div>
                </div>

                <!-- team-2 -->
                <div class="col-lg-4">
                    <div class="our-team-main">
                        <div class="team-front">
                            <img src="http://placehold.it/110x110/9c27b0/fff?text=Dilip" class="img-fluid" />
                            <h3>Dilip Kevat</h3>
                            <p>Web Designer</p>
                        </div>
                        <div class="team-back">
                            <span>
                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis 
                                natoque penatibus et magnis dis parturient montes,
                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis 
                                natoque.
                            </span>
                        </div>
                    </div>
                </div>

                <!-- team-3 -->
                <div class="col-lg-4">
                    <div class="our-team-main">
                        <div class="team-front">
                            <img src="http://placehold.it/110x110/9c27b0/fff?text=Dilip" class="img-fluid" />
                            <h3>Dilip Kevat</h3>
                            <p>Web Designer</p>
                        </div>
                        <div class="team-back">
                            <span>
                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis 
                                natoque penatibus et magnis dis parturient montes,
                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis 
                                natoque.
                            </span>
                        </div>
                    </div>
                </div>

                <!-- team-4 -->
                <div class="col-lg-4">
                    <div class="our-team-main">
                        <div class="team-front">
                            <img src="http://placehold.it/110x110/9c27b0/fff?text=Dilip" class="img-fluid" />
                            <h3>Dilip Kevat</h3>
                            <p>Web Designer</p>
                        </div>
                        <div class="team-back">
                            <span>
                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis 
                                natoque penatibus et magnis dis parturient montes,
                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis 
                                natoque.
                            </span>
                        </div>
                    </div>
                </div>

                <!-- team-5 -->
                <div class="col-lg-4">
                    <div class="our-team-main">
                        <div class="team-front">
                            <img src="http://placehold.it/110x110/9c27b0/fff?text=Dilip" class="img-fluid" />
                            <h3>Dilip Kevat</h3>
                            <p>Web Designer</p>
                        </div>
                        <div class="team-back">
                            <span>
                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis 
                                natoque penatibus et magnis dis parturient montes,
                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis 
                                natoque.
                            </span>
                        </div>
                    </div>
                </div>

                <!-- team-6 -->
                <div class="col-lg-4">
                    <div class="our-team-main">
                        <div class="team-front">
                            <img src="http://placehold.it/110x110/9c27b0/fff?text=Dilip" class="img-fluid" />
                            <h3>Dilip Kevat</h3>
                            <p>Web Designer</p>
                        </div>
                        <div class="team-back">
                            <span>
                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis 
                                natoque penatibus et magnis dis parturient montes,
                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis 
                                natoque.
                            </span>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>