<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?php if($this->selected) : ?>
    <div class="jumbotron mb-0 secondary-color">
        <h1 class="container text-center display-4"><?= $this->selectedArticle['title'] ?></h1>
    </div>
    <!-- article selected, view pdf -->
    <div class="container pb-5">
        <object class="w-100 page-90" data="<?= $this->selectedArticle['path']; ?>"></object>
        <h4 class="text-center text-muted">Not working? <a target="blank" href="<?= $this->selectedArticle['path']; ?>">Click here</a> to see pdf in separate window</h3>
    </div>
<?php endif; ?>

<div class="jumbotron mb-0 secondary-color">
    <h1 class="container display-4"><?= $this->selected ? 'Other ' : ''; ?>News</h1>
</div>

<?php foreach($this->articles as $article): ?>
    <div class="container mt-5 rounded secondary-color p-5">
        <a href="<?= $this->url('news', ['article' => preg_replace('/\\.[^.\\s]{3,4}$/', '', $article['filename'])]) ?>">
            <div class="row">
                <div class="col-md-10 col-sm-12">
                    <h2><?= $article['title'] ?></h2>
                </div>
                <?php if($article['date'] != null) : ?>
                    <!-- date set, display -->
                    <div class="text-muted text-right col-md-2 col-sm-12 my-auto"><?= $article['date']->format('d-m-y') ?></div>
                <?php endif; ?>
            </div>
        </a>
    </div>
<?php endforeach; ?>

