version: "3"

services:
  database:
    container_name: ${DB_CONTAINER_NAME}
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./data/application/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: ${SQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_PASSWORD}

  phpmyadmin:
    container_name: ${PMA_CONTAINER_NAME}
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: ${DB_CONTAINER_NAME}
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}

  website:
    container_name: ${WEB_CONTAINER_NAME}
    depends_on:
      - database
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www

  mail:
    container_name: ${MAIL_CONTAINER_NAME}
    image: tvial/docker-mailserver:latest
    hostname: ${HOST_NAME}
    domainname: ${DOMAIN_NAME}
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=1
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

volumes:
  maildata:
  mailstate:
  maillogs: