<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?php
    $form = $this->loginform;
    $form->setAttribute('action', $this->url());
    $email = $form->get('email');
    $password = $form->get('password');
    $captcha = $form->get('captcha');
    $submit = $form->get('submit');
    $form->prepare();
?>
<div class="container p-5">
    <?php if($this->message != null) : ?>
        <div class="alert alert-<?= $this->code == 1 ? "success" : "warning" ?>" role="alert"><?= $this->message ?></div>
    <?php endif; ?>
    <div class="d-flex justify-content-center">
        <div class="card">
            <div class="card-header"><h3 class="text-center">Log in</h3></div>
            <div class="card-body">
                <?= $this->form()->openTag($form); ?>
                <fieldset>
                    <div class="form-group">
                        <?= $this->formLabel($email) ?>
                        <?= $this->formElement($email) ?>
                        <?= $this->formElementErrors()->render($email) ?>
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($password) ?>
                        <?= $this->formElement($password) ?>
                        <?= $this->formElementErrors()->render($password) ?>
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($captcha) ?>
                        <?= $this->formElement($captcha) ?>
                        <?= $this->formElementErrors()->render($captcha) ?>
                    </div>
                </fieldset>

                <?php
                    echo $this->formSubmit($submit);
                    echo $this->formHidden($form->get('id'));
                    echo $this->form()->closeTag();
                ?>
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-center links">
                    <span>Don't have an account? <a href="<?= $this->url('membership/register') ?>">Sign Up</a></span>
                </div>
                <div class="d-flex justify-content-center links">
                    <span>Forgotten your password? <a href="<?= $this->url('membership/reset') ?>">Reset</a></span>
                </div>
            </div>
        </div>
    </div>
</div>
