<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="container">
    <h1>Log in</h1>
    <?php
        $form = $this->loginform;
        $form->setAttribute('action', $this->url());
        $fieldset = $form->get('post');
        $username = $fieldset->get('username');
        $password = $fieldset->get('password');
        $submit = $fieldset->get('submit');
        $form->prepare();
        echo $this->form()->openTag($form);
    ?>

    <fieldset>
        <div class="form-group">
            <?= $this->formLabel($username) ?>
            <?= $this->formElement($username) ?>
            <?= $this->formElementErrors()->render($username, ['class' => 'help-block']) ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($password) ?>
            <?= $this->formElement($password) ?>
            <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
        </div>
    </fieldset>

    <?php
        echo $this->formSubmit($submit);
        echo $this->formHidden($fieldset->get('id'));
        echo $this->form()->closeTag();
    ?>
</div>