<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="container">
    </h2><?php echo($this->message) ?></h2>
    <br/>
    <?php
        $form = $this->loginform;
        $form->setAttribute('action', $this->url());
        $fieldset = $form->get('post');
        $username = $fieldset->get('username');
        $password = $fieldset->get('password');
        $submit = $fieldset->get('submit');
        $form->prepare();
        echo $this->form()->openTag($form);
    ?>
</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Log in</div>
                <div class="card-body">
                    <fieldset>
                        <div class="form-group">
                            <?= $this->formLabel($username) ?>
                            <?= $this->formElement($username) ?>
                            <?= $this->formElementErrors()->render($username, ['class' => 'help-block']) ?>
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($password) ?>
                            <?= $this->formElement($password) ?>
                            <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
                        </div>
                    </fieldset>

                    <?php
                        echo $this->formSubmit($submit);
                        echo $this->formHidden($fieldset->get('id'));
                        echo $this->form()->closeTag();
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>