<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$user = $this->identity()['identity'];
$profilePictureForm = $this->profileImageUploadForm;
$profileimage = $profilePictureForm->get('profileimage');
$submit = $profilePictureForm->get('submit');
$profilePictureForm->prepare();
?>
<div class="jumbotron secondary-color">
    <div class="container">
        <h1 class="display-4"><i class="fa fa-user-cog primary-text"></i> <?= $user['firstname'] . ' ' . $user['surname'] ?></h1>
    </div>
</div>

<?php if($this->message != null) : ?>
    <!-- message from controller -->
    <div class="container alert-dismissible fade show alert alert-<?= $this->messageAlert ?>" role="alert">
        <?= $this->message ?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"><i class="fa fa-times"></i></span>
        </button>
    </div>
<?php endif; ?>

<div class="container">
    <div class="row">
        <div class="col-lg-3 col-sm-12 mb-3">
            <img src="<?= $user['profilepicture64'] ?>" class="img-circle img-thumbnail" alt="Profile picture">
            <?= $this->form()->openTag($profilePictureForm); ?>
            <fieldset>

                <div class="form-group">
                    <div class="text-center text-muted">
                        <?= $this->formLabel($profileimage) ?>
                    </div>
                    <?= $this->formSubmit($submit); ?>
                    <?= $this->formElement($profileimage) ?>
                    <?= $this->formElementErrors()->render($profileimage, ['class' => 'text-danger']) ?>
                </div>

            </fieldset>

            <?= $this->formHidden($profilePictureForm->get('id')); ?>
            <?= $this->form()->closeTag(); ?>
        </div>

        <div class="col-lg-9 col-sm-12">
            <form class="form" action="##" method="post" id="registrationForm">
                <div class="form-group">
                    <label for="first_name"><h4>First name</h4></label>
                    <input type="text" class="form-control" name="first_name" id="first_name" placeholder="<?= $user['firstname'] ?>" title="enter your first name if any.">
                </div>
                <div class="form-group">
                    <label for="last_name"><h4>Last name</h4></label>
                    <input type="text" class="form-control" name="last_name" id="last_name" placeholder="<?= $user['surname'] ?>" title="enter your last name if any.">
                </div>
                <div class="form-group">
                    <label for="email"><h4>Email</h4></label>
                    <input type="email" class="form-control" name="email" id="email" placeholder="<?= $user['email'] ?>" title="enter your email.">
                </div>
                <div class="form-group">
                    <button class="btn btn-lg btn-primary" type="submit"><i class="fa fa-save"></i> Save</button>
                    <button class="btn btn-lg btn-secondary" type="reset"><i class="fa fa-redo"></i> Reset</button>
                </div>
            </form>
        </div>
    </div>
</div>