<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <?php if($this->message != null) : ?>
                <div class="alert alert-warning" role="alert"><?= $this->message ?></div>
            <?php endif; ?>
            <?php
                $form = $this->registerform;
                $form->setAttribute('action', $this->url());
                $username = $form->get('username');
                $name = $form->get('name');
                $email = $form->get('email');
                $password = $form->get('password');
                $passwordConfirm = $form->get('password-confirm');
                $submit = $form->get('submit');
                $form->prepare();
            ?>
        </div>
    </div>
</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Register</div>
                <div class="card-body">
                    <?= $this->form()->openTag($form); ?>
                    <fieldset>
                        <div class="form-group">
                            <?= $this->formLabel($username) ?>
                            <?= $this->formElement($username) ?>
                            <?= $this->formElementErrors()->render($username, ['class' => 'help-block']) ?>
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($name) ?>
                            <?= $this->formElement($name) ?>
                            <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($email) ?>
                            <?= $this->formElement($email) ?>
                            <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($password) ?>
                            <?= $this->formElement($password) ?>
                            <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($passwordConfirm) ?>
                            <?= $this->formElement($passwordConfirm) ?>
                            <?= $this->formElementErrors()->render($passwordConfirm, ['class' => 'help-block']) ?>
                        </div>
                    </fieldset>

                    <?php
                        echo $this->formSubmit($submit);
                        echo $this->formHidden($form->get('id'));
                        echo $this->form()->closeTag();
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>