<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
if ($this->registerform != null) {
    $form = $this->registerform;
    $form->setAttribute('action', $this->url());
    $firstname = $form->get('firstname');
    $surname = $form->get('surname');
    $email = $form->get('email');
    $password = $form->get('password');
    $passwordConfirm = $form->get('password-confirm');
    $captcha = $form->get('captcha');
    $submit = $form->get('submit');
    $form->prepare();
}
?>

<?php if($this->message != null) : ?>
    <!-- message container -->
    <div class="container pt-5">
        <div class="d-flex justify-content-center">
            <div class="alert alert-<?= $this->success ? 'success' : 'warning'?>" role="alert"> <?= $this->message ?> </div>
        </div>
    </div>
<?php endif; ?>

<?php if($this->registerform != null) : ?>
    <!-- render registration form -->
    <div class="container p-5">
        <div class="d-flex justify-content-center">
                <div class="card">
                    <div class="card-header"><h3 class="text-center">Register</h3></div>
                    <div class="card-body">
                        <?= $this->form()->openTag($form); ?>
                        <fieldset>
                            <div class="form-group">
                                <?= $this->formLabel($firstname) ?>
                                <?= $this->formElement($firstname) ?>
                                <?= $this->formElementErrors()->render($firstname) ?>
                            </div>

                            <div class="form-group">
                                <?= $this->formLabel($surname) ?>
                                <?= $this->formElement($surname) ?>
                                <?= $this->formElementErrors()->render($surname) ?>
                            </div>

                            <div class="form-group">
                                <?= $this->formLabel($email) ?>
                                <?= $this->formElement($email) ?>
                                <?= $this->formElementErrors()->render($email) ?>
                            </div>

                            <div class="form-group">
                                <?= $this->formLabel($password) ?>
                                <?= $this->formElement($password) ?>
                                <?= $this->formElementErrors()->render($password) ?>
                            </div>

                            <div class="form-group">
                                <?= $this->formLabel($passwordConfirm) ?>
                                <?= $this->formElement($passwordConfirm) ?>
                                <?= $this->formElementErrors()->render($passwordConfirm) ?>
                            </div>

                            <div class="form-group">
                                <?= $this->formLabel($captcha) ?>
                                <?= $this->formElement($captcha) ?>
                                <?= $this->formElementErrors()->render($captcha) ?>
                            </div>
                        </fieldset>

                        <?php
                            echo $this->formSubmit($submit);
                            echo $this->formHidden($form->get('id'));
                            echo $this->form()->closeTag();
                        ?>
                    </div>
                    <div class="card-footer">
                        <div class="d-flex justify-content-center links">
                            Already have an account? <a href="<?= $this->url('membership/login') ?>">Log In</a>
                        </div>
                    </div>

            </div>
        </div>
    </div>
<?php endif; ?>