<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?php
if($this->resetForm != null) {
    $form = $this->resetForm;
    $form->setAttribute('action', $this->url());
    $email = $form->get('email');
    $submit = $form->get('submit');
    $form->prepare();
}
?>

<?php if($this->resetForm != null) : ?>
    <!-- form passed to view, render it -->
    <div class="container p-5">
        <?php if($this->message != null) : ?>
            <div class="alert " role="alert"><?= $this->message ?></div>
        <?php endif; ?>
        <div class="d-flex justify-content-center">
            <div class="card">
                <div class="card-header"><h3 class="display-5">Reset Password</h3></div>
                <div class="card-body">
                    <?= $this->form()->openTag($form); ?>
                    <fieldset>
                        <div class="form-group">
                            <?= $this->formLabel($email) ?>
                            <?= $this->formElement($email) ?>
                            <?= $this->formElementErrors()->render($email) ?>
                        </div>
                    </fieldset>

                    <?php
                        echo $this->formSubmit($submit);
                        echo $this->formHidden($form->get('id'));
                        echo $this->form()->closeTag();
                    ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
