<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron mb-5 secondary-color">
    <div class="container">
        <h1 class="display-4">Training</h1>
    </div>
</div>

<!-- intro text -->
<div class="container-fluid tb-5">
    <div class="row justify-content-center text-center">
        <div class="col-xl-4 col-lg-6 col-md-12 p-5 align-self-center">
            <p class="lead">Training is available to all Club Members only. To take part in any training sessions, you must first <a href="<?= $this->url('join') ?>" >join the club and become a member</a>.</p>
            <p class="lead">Training and membership of the club is open to almost anyone. You do not need to be employed by Tata Steel to join the club and start a training course.</p>
            <p class="lead">
                The club is recognised by the Royal Yachting Association (RYA) as an approved training centre offering dinghy sailing, powerboat, safety boat, and 1st aid courses.
                Our instructors hold the appropriate RYA qualifications.
                Why not visit the club on a Sunday to gain an understanding of our activities?
                Any of our members will be able to direct you to one of our instructors.
            </p>
        </div>
        <div class="col-xl-5 col-lg-6 col-md-12 p-5 align-self-center">
            <img class="rounded shadow w-100" src="<?= $this->basePath('/img/training1.jpg') ?>">
        </div>
    </div>
</div>

<!-- links to sail/wind/race/power pages -->
<div class="container-fluid">
    <div class="row justify-content-lg-center text-center">
        <div class="col-xl-3 col-lg-4 p-5 m-5">
            <h3 class="page-header pb-3 mb-3 ">Sailing/Windsurfing</h3>
            <p class="lead">
                These courses are suited for all levels of experience.
                Whether you are a complete beginner looking to find your sea legs,
                or a more experienced sailer looking to touch up your skills,
                you will find the courses fun and educational.
            </p>
            <a role="button" class="btn btn-primary" href="<?= $this->url('training/sailing') ?>">Discover more <i class="fa fa-angle-double-right"></i></a>
        </div>
        <div class="col-xl-3 col-lg-4 p-5 m-5">
            <h3 class="page-header pb-3 mb-3 ">Racing</h3>
            <p class="lead">
                "Start Racing" courses are held in June and July,
                and will teach you the necessary rules you will need to know in order to take part in a sailing race.
            </p>
            <a role="button" class="btn btn-primary" href="<?= $this->url('training/racing') ?>">Discover more <i class="fa fa-angle-double-right"></i></a>
        </div>
        <div class="col-xl-3 col-lg-4 p-5 m-5">
            <h3 class="page-header pb-3 mb-3">Powerboating</h3>
            <p class="lead">
                RYA Powerboat / safety boat level 1 and 2 courses are held to ensure our sailing members have the necessary
                skills and knowledge to operate the patrol boats competently and safely.
            </p>
            <p class="lead">
                The courses prepare members for their roster duties, and provide a pathway to becoming dinghy instructors.
            </p>
            <a role="button" class="btn btn-primary" href="<?= $this->url('training/powerboat') ?>">Discover more <i class="fa fa-angle-double-right"></i></a>
        </div>
    </div>
</div>