<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron mb-5 secondary-color">
    <div class="container">
        <h1 class="display-4">Powerboat Training</h1>
    </div>
</div>

<div class="container">
    <p>Powerboat Training is given to enable the support club sailing activities</p>
    <p>Please note that we may not be able to offer training or membership to persons with certain medical conditions, or perambulatory and certain other disabilities, It is important to discuss this when you first contact Jeremy Martin on 01656 861092.</p>
    <p>Contact our Training Principal (training@tatasteelsailing.org.uk) about Powerboat training to find out more.</p>
</div>