<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron mb-5 secondary-color">
    <div class="container">
        <h1 class="display-4">Racing Training</h1>
    </div>
</div>

<div class="container">
    <p>These courses will teach you what you need to know to compete in a sailboat race, and will cover all the rules that a racer will need to know.</p>
    <p>Upon completion, you will be confident and competent at taking part in racing on the water. There is plenty of opportunity to discuss racing tactics, rules and general applications during our friendly racing series' and events.</p>
    <p>The course duration will be one day, with different aspects of racing being attended to on different courses.</p>
    <p>Contact our Training Principal (training@tatasteelsailing.org.uk) about Racing courses to find out more.</p>
    <p>Please note that we may not be able to offer training or membership to persons with certain medical conditions, or perambulatory and certain other disabilities, It is important to discuss this when you first contact Jeremy Martin on 01656 861092.</p>
</div>