<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron mb-5 secondary-color">
    <div class="container">
        <h1 class="display-4">Sailing Training</h1>
    </div>
</div>

<div class="container pb-5">
    <h2 class="page-header pb-3 mb-3">The sailing course covers:</h2>
    <ul class="list-group pb-5">
        <li class="list-group-item">The correct clothing / equipment</li>
        <li class="list-group-item">Safety on and off the water</li>
        <li class="list-group-item">Understanding the weather</li>
        <li class="list-group-item">Ropework</li>
        <li class="list-group-item">Rigging and boat preparation for sailing</li>
        <li class="list-group-item">Sailing and tacking</li>
        <li class="list-group-item">Sailing terminology</li>
        <li class="list-group-item">The 5 essentials - boat and sail handling</li>
        <li class="list-group-item">Sailing the triangular course</li>
        <li class="list-group-item">Basic rules of sailing</li>
        <li class="list-group-item">Coming alongside / pick up a mooring</li>
        <li class="list-group-item">Recover a man overboard</li>
        <li class="list-group-item">Taking a tow</li>
        <li class="list-group-item">Launching and landing - best approach</li>
        <li class="list-group-item">Capsize and recovery</li>
        <li class="list-group-item">An understanding of racing</li>
    </ul>
    <p>A mix of classroom and water based training is practiced during the whole course, commencing with a safety briefing and getting to know the dinghy. The aim is to get you on the water as soon as possible.</p>
    <p>All trainees will achieve either RYA Level 1 or 2 qualifications, will be able to helm a dinghy safely and competently in good conditions, and have the ability to make the correct decisions on the water and onshore.</p>
    <p>Please note that we may not be able to offer training or membership to persons with certain medical conditions, or perambulatory and certain other disabilities, It is important to discuss this when you first contact Jeremy Martin on 01656 861092.</p>
    <p>Training Courses will normally be run over 4 days or equivalent hours, but a flexible approach will be considered if you need more time.</p>
    <p>Once training has been completed you are able to use the club boats in light wind conditions if they are not being used for training.</p>
</div>
