<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$user = $this->identity()['identity'];
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Rhydian\'s website')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="Laminas">
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('home') ?>">Home</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('about') ?>">About</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('gallery') ?>">Gallery</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('membership') ?>">Membership</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <?php if($user != null) : ?>
                            <li class="nav-item active">
                                <a class="nav-link" href="<?= $this->url('membership/logout') ?>">Hello, <?= $user ?> (Log out)</a>
                            </li>
                        <?php else : ?>
                            <li class="nav-item active">
                                <a class="nav-link" href="<?= $this->url('membership/login') ?>">Log in</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="<?= $this->url('membership/register') ?>">Register</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            <?= $this->content ?>
        </div>
        <div class="container-fluid">
            <hr>
            <footer class="d-flex justify-content-center m-0 p-0">
                <div class="row row-centered">
                    <div class="col-lg-4 col-sm-12 text-center">
                        <img class="rounded-circle footer-img" src="<?= '/img/tssc_logo.jpg'; ?>" alt="Club Logo" />
                    </div>

                    <div class="col-lg-4 col-sm-12 text-center">
                        <h4><?= date('Y') ?> Tata Steel Sailing Club</h4>
                        <address>
                            Eglwys Nunydd Reservoir<br />
                            Off Longlands Lane<br />
                            Margam<br />
                            Port Talbot<br />
                            SA13 2NS
                        </address>
                    </div>

                    <div class="col-lg-4 col-sm-12 text-center">
                        <img class="rounded-circle footer-img" src="<?= '/img/RYA_TC_Logo.jpg'; ?>" alt="RYA Approved" />
                    </div>
                </div>
            </footer>
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
    </body>
</html>
