<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$user = $this->identity() == null ? null : $this->identity()['identity'];
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Tata Steel Sailing')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/fa.all.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="Laminas">
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('home') ?>">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="aboutDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">About</a>
                            <div class="dropdown-menu" aria-labelledby="aboutDropdown">
                                <a class="dropdown-item" href="<?= $this->url('about/club') ?>">The Club</a>
                                <a class="dropdown-item" href="<?= $this->url('about/team') ?>">Our Team</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('gallery') ?>">Gallery</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('news') ?>">News</a>
                        </li>
                        <?php if($user != null) : ?>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= $this->url('membership/my_account') ?>">My Account</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <?php if($user != null) : ?>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= $this->url('membership/logout') ?>">Hello, <?= $user['firstname'] ?> (Log out)</a>
                            </li>
                        <?php else : ?>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= $this->url('membership/login') ?>">Log in</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= $this->url('membership/register') ?>">Register</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>

        <?= $this->content ?>

        <footer class="primary-color pt-5">
            <div class="container">
                <div class="row">
                    <!-- address -->
                    <div class="col-lg-4 col-sm-12 mb-4 text-center">
                        <h5><i class="fa fa-map-marker-alt"></i> Address</h5>
                        <address>
                            Eglwys Nunydd Reservoir<br />
                            Off Longlands Lane<br />
                            Margam<br />
                            Port Talbot<br />
                            SA13 2NS
                        </address>
                    </div>

                    <!-- images -->
                    <div class="col-lg-4 col-sm-12 mb-4 text-center">
                        <img class="rounded-circle footer-img" src="<?= '/img/tssc_logo.jpg'; ?>" alt="Club Logo" />
                        <img class="rounded-circle footer-img" src="<?= '/img/RYA_TC_Logo.jpg'; ?>" alt="RYA Approved" />
                    </div>

                    <!-- contact -->
                    <div class="col-lg-4 col-sm-12 mb-4 text-center">
                        <h5><i class="fa fa-envelope"></i> Contact</h5>
                        <a href="mailto:membership@tatasteelsailing.org.uk">membership@tatasteelsailing.org.uk</a><br />
                        <a href="mailto:training@tatasteelsailing.org.uk">training@tatasteelsailing.org.uk</a><br />
                        <a href="mailto:webmaster@tatasteelsailing.org.uk">webmaster@tatasteelsailing.org.uk</a>
                    </div>
                </div>
            </div>

            <div class="faded-bg text-center p-2 text-muted">
                <h5><i class="fa fa-copyright"></i> <?= date('Y') ?> Tata Steel Sailing Club</h5>
            </div>
        </footer>

        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js'))
            ->prependFile('http://maps.google.com/maps/api/js?key=AIzaSyBL4LO7Tj2Ao6LdcFYFlC9Kf0Lo5__QYzQ')
        ?>
    </body>
</html>
