<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$user = $this->identity() == null ? null : $this->identity()['identity'];
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Tata Steel Sailing')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/footer-waves.css'))
        ?>

        <?php if (isset($stylesheet)): ?>
            <!-- page specific styles -->
            <?= $this->headLink()->prependStylesheet($this->basePath($stylesheet)); ?>
        <?php endif; ?>

        <!-- Head Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/fa.all.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js'))
        ?>
    </head>
    <body>
        <!-- nav bar -->
        <nav id="navigationbar" class="navbar fixed-top navbar-expand-xl navbar-dark" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <h3 class="logo">Tata Steel Sailing</h2>
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('home') ?>">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="aboutDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">About</a>
                            <div class="dropdown-menu" aria-labelledby="aboutDropdown">
                                <a class="dropdown-item" href="<?= $this->url('about') ?>">The Club</a>
                                <a class="dropdown-item" href="<?= $this->url('about/team') ?>">Our Team</a>
                                <a class="dropdown-item" href="<?= $this->url('sailing/pn') ?>">Club Portsmouth Numbers</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="aboutDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sailing</a>
                            <div class="dropdown-menu" aria-labelledby="aboutDropdown">
                                <a class="dropdown-item" href="<?= $this->url('sailing/results') ?>">Results</a>
                                <a class="dropdown-item" href="<?= $this->url('sailing/instructions') ?>">Instructions</a>
                                <a class="dropdown-item" href="<?= $this->url('sailing/book') ?>">Book a Session</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('gallery') ?>">Gallery</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('news') ?>">News</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('training') ?>">Training</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('calendar') ?>">Calendar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://apex.oracle.com/pls/apex/f?p=76809:1" target="_blank">OOD Rota</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <?php if($user != null) : ?>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= $this->url('membership/my_account') ?>">My Account</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= $this->url('membership/logout') ?>">Log out</a>
                            </li>
                        <?php else : ?>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= $this->url('membership/login') ?>">Log in</a>
                            </li>
                            <li class="nav-item">
                                <button class="btn tertiary-color primary-text shadow font-weight-bold" onclick="location.href='<?= $this->url('join') ?>'">Join Us</button>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>

        <!-- page content -->
        <div class="content">
            <?= $this->content ?>
        </div>

        <!-- footer waves -->
        <div>
            <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
                <defs>
                    <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
                </defs>
                <g class="parallax">
                    <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(var(--primary-color-rgb), 0.75)" />
                    <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(var(--primary-color-rgb), 0.5)" />
                    <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(var(--primary-color-rgb), 0.25)" />
                    <use xlink:href="#gentle-wave" x="48" y="7" fill="var(--primary-color)" />
                </g>
            </svg>
        </div>

        <!-- footer -->
        <footer id="wave-footer" class="page-footer font-small primary-color pt-4">
            <div class="container">
                <div class="row">
                    <!-- address -->
                    <div class="col-lg-4 col-sm-12 mb-4 text-center">
                        <h5><i class="fa fa-map-marker-alt"></i> Address</h5>
                        <address>
                            Eglwys Nunydd Reservoir<br />
                            Off Longlands Lane<br />
                            Margam<br />
                            Port Talbot<br />
                            SA13 2NS
                        </address>
                    </div>

                    <!-- images -->
                    <div class="col-lg-4 col-sm-12 mb-4 text-center">
                        <img class="rounded-circle" src="<?= $this->basePath('/img/tssc_logo.jpg') ?>" alt="Club Logo" />
                        <img class="rounded-circle" src="<?= $this->basePath('/img/RYA_TC_Logo.jpg') ?>" alt="RYA Approved" />
                    </div>

                    <!-- contact -->
                    <div class="col-lg-4 col-sm-12 mb-4 text-center">
                        <h5><i class="fa fa-envelope"></i> Contact</h5>
                        <a href="mailto:membership@tatasteelsailing.org.uk">membership@tatasteelsailing.org.uk</a><br />
                        <a href="mailto:training@tatasteelsailing.org.uk">training@tatasteelsailing.org.uk</a><br />
                        <a href="mailto:webmaster@tatasteelsailing.org.uk">webmaster@tatasteelsailing.org.uk</a>
                    </div>
                </div>
                <div class="row">
                    <h7 class="p-3 text-center col-lg-12"><i class="fa fa-copyright"></i> <?= date('Y') ?> Tata Steel Sailing Club</h7>
                    <p class="text-center col-lg-12" title="Back to top"><a href="#"><i class="fa fa-chevron-up"></i></a></p>
                </div>
            </div>
        </footer>
    </body>

    <!-- js -->
    <?= $this->inlineScript() ?>
</html>
