<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Welcome to the gallery</h1>
</div>

<!-- <div class="row justify-content-center"> -->
<div class="row justify-content-center">
    <?php foreach($this->albums as $album): ?>
        <div class="col-lg-2 col-md-3 col-sm-6 col-xs-12 col-centered thumb pointer-hover padding-0 sr2">
            <a class="thumbnail" href="<?= $this->url('gallery') ?>">
                <img class="img-fluid center-block" src="<?= $album['thumbnail'] ?>">
                <p class="text-center padding-10 margin-0" style="white-space: nowrap;"><?= $album['title'] ?></p>
            </a>
        </div>
    <?php endforeach; ?>
</div>
