<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron secondary-color">
    <h1 class="container display-4"><a href="<?= $this->url('gallery') ?>">Albums</a><?= $this->imagesFound ? (' / ' . $this->albumName) : '' ?></h1>
</div>


<?php if($this->imagesFound) : ?>
    <!-- display images in given album -->
    <div class="masonry-grid">
        <div class="grid-sizer"></div>
            <?php foreach($this->images as $image): ?>
                <div class="grid-item p-1">
                    <img data-toggle="modal" data-target="#imageModal" src="<?= $this->basePath($image['path'] . $image['filename']) ?>">
                </div>
            <?php endforeach; ?>
        </div>
    </div>

    <!-- image modal -->
    <div id="imageModal" class="modal fade shadow-lg" role="dialog">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-body">
                    <img id="large-image" class="w-100 h-100" src="" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <?php
        // add js driving modal
        $this->inlineScript()->captureStart();
        echo <<<JS
            $(document).ready(function () {
                $('#imageModal').on('show.bs.modal', function (e) {
                    var image = $(e.relatedTarget).attr('src');
                    $("#large-image").attr("src", image);
                });
            });
        JS;
        $this->inlineScript()->captureEnd();
    ?>
<?php else: ?>
    <!-- display all albums -->
    <div class="masonry-grid">
        <div class="grid-sizer"></div>
        <?php foreach($this->albums as $album): ?>
            <a class="grid-item p-1" href="<?= $this->url('gallery', ['album' => $album['name']]) ?>">
                <img src="<?= $album['thumbnail'] ?>">
                <div class="p-3 primary-color rounded-bottom">
                    <p class="text-center m-0"><?= $album['title'] ?></p>
                </div>
            </a>
        <?php endforeach; ?>
    </div>
<?php endif; ?>

<?= $this->inlinescript()->prependFile($this->basePath('/js/masonry.dkgd.min.js')); ?>
<?= $this->inlineScript()->prependFile($this->basePath('/js/imagesloaded.pkgd.min.js')); ?>
<?= $this->inlineScript()->prependFile($this->basePath('/js/masonry.driver.js')); ?>