<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron secondary-color">
    <div class="container">
        <h1 class="display-4">The Main Page</h1>
        <hr class="my-4">
        <a class="btn btn-primary btn-lg" href="https://github.com/rhydianjenkins" target="_blank">Check out my GitHub &raquo;</a>
    </div>
</div>

<div class="container">
    <div class="card-deck">
        <div class="card">
            <h2 class="card-header">Card 1</h2>
            <div class="card-body">
                <p>
                    This is card 1.
                </p>
            </div>
        </div>

        <div class="card">
            <h2 class="card-header">Card 2</h2>
            <div class="card-body">
                <p>
                    This is card 2.
                </p>
            </div>
        </div>

        <div class="card">
            <h2 class="card-header">Card 3</h2>
            <div class="card-body">
                <p>This is card 3.</p>
            </div>
        </div>
    </div>
</div>
