<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<!-- main page carousel -->
<div id="carouselExampleIndicators" class="m-0 carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <!-- Slide One: Sailing -->
        <div class="carousel-item active" style="background-image: url('img/front-page-sailing.jpg')">
        <div class="carousel-caption rounded pl-3 pr-3 faded-bg">
            <h3 class="h3-responsive">Sailing</h2>
            <p class="lead">The reservoir is over one mile long by approximately half a mile wide, where cruising can be enjoyed under the safe visibility of the on-duty safety boat crews.</p>
            <p class="lead">Tuesday evenings through the Spring and Summer months provide a safe environment for casual sailing as well as the opportunity to practice skills in a non-raciing environment.</p>
        </div>
        </div>
        <!-- Slide Two: Windsurfing -->
        <div class="carousel-item" style="background-image: url('img/front-page-windsurfing.jpg')">
        <div class="carousel-caption rounded pl-3 pr-3 faded-bg">
            <h3 class="h3-responsive">Windsurfing</h2>
            <p class="lead">Whatever your ability, the Lake is ideal for windsurfing in most wind directions, with a spacious grassy area for rigging, and an easy launching area.</p>
            <p class="lead">You don’t have to worry about tides and you can enjoy the luxury of hot showers, hot drinks and the chance to have a chat with other members.</p>
        </div>
        </div>
        <!-- Slide Three: Racing -->
        <div class="carousel-item" style="background-image: url('img/front-page-racing.jpg')">
        <div class="carousel-caption rounded pl-3 pr-3 faded-bg">
            <h3 class="h3-responsive">Racing</h2>
            <p class="lead">We have racing all year round at the club, as the resevior is warm enough to sail in without too much discomfort even in the winter months. During the warmer months we have racing three days a week as well as various class and club regattas.</p>
            <p class="lead">You will find club racing competitive and friendly at the same time in both the General Handicap Fleet as well as the well established Solo Class Fleet.</p>
        </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<!-- faq -->
<div class="container-fluid">
    <div class="container pt-5 pb-5">
        <h2 class="page-header pb-3 mb-3 text-center">Frequently Asked Questions</h2>
        <div class="panel-group" id="faq">
            <div class="cursor-pointer pb-3">
                <div class="panel-heading accordion-toggle collapsed" data-toggle="collapse" data-parent="#faq" href="#collapseOne">
                    <h4 class="panel-title">
                        <a class="accordion-toggle collapsed" data-toggle="collapse">Do I need to be an employee of Tata Steel to join the club?</a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse">
                    <div class="panel-body">
                        No, anyone can join the club - not just Tata Steel employees! Associate Members make up the bulk of the club's membership
                    </div>
                </div>
            </div>
            
            <div class="cursor-pointer pb-3">
                <div class="panel-heading accordion-toggle collapsed" data-toggle="collapse" data-parent="#faq" href="#collapseTwo">
                    <h4 class="panel-title">
                        <a class="accordion-toggle collapsed" data-toggle="collapse">Where do I apply to join Tata Steel Sailing Club?</a>
                    </h4>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse">
                    <div class="panel-body">
                        You can download an application form from this website or pick one up from the club. You are welcome to the club at any time we are open. Please look at the calendar to see when we are there
                    </div>
                </div>
            </div>
            
            <div class="cursor-pointer pb-3">
                <div class="panel-heading accordion-toggle collapsed" data-toggle="collapse" data-parent="#faq" href="#collapseThree">
                    <h4 class="panel-title">
                        <a class="accordion-toggle collapsed" data-toggle="collapse">When is Tata Steel Sailing Club open?</a>
                    </h4>
                </div>
                <div id="collapseThree" class="panel-collapse collapse">
                    <div class="panel-body">
                        Times and dates vary through the seasons, check the calendar for planned activities. Might be an idea to contact a member first and arrange a visit, although you are very welcome to just turn up at any time we're there
                    </div>
                </div>
            </div>
            
            <div class="cursor-pointer pb-3">
                <div class="panel-heading accordion-toggle collapsed" data-toggle="collapse" data-parent="#faq" href="#collapseFour">
                    <h4 class="panel-title">
                        <a class="accordion-toggle collapsed" data-toggle="collapse">How much does it cost to join the club?</a>
                    </h4>
                </div>
                <div id="collapseFour" class="panel-collapse collapse">
                    <div class="panel-body">
                        Membership fees vary depending on your circumstances. Download the application form, it details the various offers. The Membership Secretary can help you choose the best option for you if you need help
                    </div>
                </div>
            </div>
            
            <div class="cursor-pointer pb-3">
                <div class="panel-heading accordion-toggle collapsed" data-toggle="collapse" data-parent="#faq" href="#collapseFive">
                    <h4 class="panel-title">
                        <a class="accordion-toggle collapsed" data-toggle="collapse">Are there any age restrictions?</a>
                    </h4>
                </div>
                <div id="collapseFive" class="panel-collapse collapse">
                    <div class="panel-body">
                        We've had sailing members from 8 years old to 85. Physical fitness is more important than age. Sailing is one of those hobbies that suits all. You just need to pick the boat that suits you.
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- map -->
<div class="container-fluid p-0">
    <div id="gmap_canvas" class="page-90">
        <style>#gmap_canvas img{max-width:none!important;background:none!important}</style>
    </div>
</div>
