<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<!-- main page carousel -->
<div id="carouselExampleIndicators" class="m-0 carousel slide border-bottom" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <!-- Slide One: Sailing -->
        <div class="carousel-item active" style="background-image: url('<?= $this->basePath('/img/front-page-sailing.jpg') ?>')">
        <div class="carousel-caption rounded pl-3 pr-3 faded-bg">
            <h3 class="h3-responsive">Sailing</h2>
        </div>
        </div>
        <!-- Slide Two: Windsurfing -->
        <div class="carousel-item" style="background-image: url('<?= $this->basePath('/img/front-page-windsurfing.jpg') ?>')">
        <div class="carousel-caption rounded pl-3 pr-3 faded-bg">
            <h3 class="h3-responsive">Windsurfing</h2>
        </div>
        </div>
        <!-- Slide Three: Racing -->
        <div class="carousel-item" style="background-image: url('<?= $this->basePath('/img/front-page-racing.jpg') ?>')">
        <div class="carousel-caption rounded pl-3 pr-3 faded-bg">
            <h3 class="h3-responsive">Racing</h2>
        </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<!-- sail, wind, race -->
<div class="container-fluid pt-5">
    <div class="row justify-content-lg-center text-center">
        <div class="col-lg-3 p-5 m-5">
            <h3 class="page-header pb-3 mb-3 ">Sailing</h3>
            <p>The reservoir is over one mile long by approximately half a mile wide, where cruising can be enjoyed under the safe visibility of the on-duty safety boat crews.</p>
            <p>Tuesday evenings through the Spring and Summer months provide a safe environment for casual sailing as well as the opportunity to practice skills in a non-raciing environment.</p>
        </div>
        <div class="col-lg-3 p-5 m-5">
            <h3 class="page-header pb-3 mb-3 ">Windsurfing</h3>
            <p>Whatever your ability, the Lake is ideal for windsurfing in most wind directions, with a spacious grassy area for rigging, and an easy launching area.</p>
            <p>You don’t have to worry about tides and you can enjoy the luxury of hot showers, hot drinks and the chance to have a chat with other members.</p>
        </div>
        <div class="col-lg-3 p-5 m-5">
            <h3 class="page-header pb-3 mb-3">Racing</h3>
            <p>We have racing all year round at the club, as the resevior is warm enough to sail in without too much discomfort even in the winter months. During the warmer months we have racing three days a week as well as various class and club regattas.</p>
            <p>You will find club racing competitive and friendly at the same time in both the General Handicap Fleet as well as the well established Solo Class Fleet.</p>
        </div>
    </div>
</div>

<!-- weather -->
<div class="container-fluid pt-5">
    <h2 class="container page-header pb-3 mb-3 text-center">Margam Weather</h2>
    <?php if($this->weatherOk): ?>
        <div class="row">
            <?php foreach($this->weather as $date => $forecast): ?>
                <div id="<?= $forecast['date_epoch'] ?>" class="col-xl-4 rounded">
                    <h3 class="text-center"><?= $date ?></h3>
                    <table class="table shadow table-striped table-hover table-sm weather-table border-bottom-table">
                        <thead class="primary-color">
                            <tr>
                                <th scope="col">Hour</th>
                                <th scope="col">Wind (mph)</th>
                                <th scope="col">Gust (mph)</th>
                                <th scope="col">Temp</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody class="secondary-color">
                            <?php foreach($forecast['hour'] as $hour => $data): ?>
                                <?php if(new DateTime('@' . $data['time_epoch']) > new DateTime()): ?>
                                    <tr>
                                        <td><?= date("H:i", strtotime($hour.':00')) ?></td>
                                        <td><i class="fa fa-arrow-up" style="transform: rotate(<?= $data['wind_degree'] ?>deg)"></i> <?= $data['wind_mph'] ?></td>
                                        <td><?= $data['gust_mph'] ?></td>
                                        <td><?= $data['temp_c'] ?>&deg;</td>
                                        <td><img class="img-fluid"  src="<?= $data['condition']['icon'] ?>" alt="condition"></img></td>
                                    </tr>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php endforeach;?>
        </div>
        <!-- credit to WeatherAPI.com -->
        <h6 class="text-muted text-right">
            Powered by <a target="blank" href="https://www.weatherapi.com/" title="Free Weather API">WeatherAPI.com</a>
        </h6>
    <?php else: ?>
        <p>Oops! Something went wrong when loading weather, check back later.</p>
    <?php endif; ?>
</div>

<!-- map -->
<div class="container-fluid p-0">
    <div id="gmap_canvas" class="page-90">
        <style>#gmap_canvas img{max-width:none!important;background:none!important}</style>
    </div>
</div>

<!-- faq -->
<div class="container-fluid">
    <div class="container pt-5 pb-5">
        <h2 class="page-header pb-3 mb-3 text-center">Frequently Asked Questions</h2>
        <div class="panel-group" id="faq">

            <div class="cursor-pointer mb-3">
                <div class="shadow-sm panel-heading accordion-toggle collapsed secondary-color rounded p-3" data-toggle="collapse" data-parent="#faq" href="#collapseOne">
                    <h4 class="panel-title">
                        <a class="accordion-toggle collapsed" data-toggle="collapse">Do I need to be an employee of Tata Steel to join the club?</a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse">
                    <div class="panel-body">
                        No, anyone can join the club - not just Tata Steel employees! Associate Members make up the bulk of the club's membership.
                    </div>
                </div>
            </div>
            
            <div class="cursor-pointer mb-3">
                <div class="shadow-sm panel-heading accordion-toggle collapsed secondary-color rounded p-3" data-toggle="collapse" data-parent="#faq" href="#collapseTwo">
                    <h4 class="panel-title">
                        <a class="accordion-toggle collapsed" data-toggle="collapse">Where do I apply to join Tata Steel Sailing Club?</a>
                    </h4>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse">
                    <div class="panel-body">
                        Click on the "Join Us" page above and choose the appropriate application form from this website.
                        You are welcome to the club at any time we are open. Please look at the calendar to see when we are there.
                    </div>
                </div>
            </div>
            
            <div class="cursor-pointer mb-3">
                <div class="shadow-sm panel-heading accordion-toggle collapsed secondary-color rounded p-3" data-toggle="collapse" data-parent="#faq" href="#collapseThree">
                    <h4 class="panel-title">
                        <a class="accordion-toggle collapsed" data-toggle="collapse">When is Tata Steel Sailing Club open?</a>
                    </h4>
                </div>
                <div id="collapseThree" class="panel-collapse collapse">
                    <div class="panel-body">
                        Times and dates vary through the seasons, check the calendar for planned activities.
                        Might be an idea to contact a member first and arrange a visit, although you are very welcome to just turn up at any time we're there.
                    </div>
                </div>
            </div>
            
            <div class="cursor-pointer mb-3">
                <div class="shadow-sm panel-heading accordion-toggle collapsed secondary-color rounded p-3" data-toggle="collapse" data-parent="#faq" href="#collapseFour">
                    <h4 class="panel-title">
                        <a class="accordion-toggle collapsed" data-toggle="collapse">How much does it cost to join the club?</a>
                    </h4>
                </div>
                <div id="collapseFour" class="panel-collapse collapse">
                    <div class="panel-body">
                        Membership fees vary depending on your circumstances.
                        Download the application form, it details the various offers.
                        The Membership Secretary can help you choose the best option for you if you need help.
                    </div>
                </div>
            </div>
            
            <div class="cursor-pointer mb-3">
                <div class="shadow-sm panel-heading accordion-toggle collapsed secondary-color rounded p-3" data-toggle="collapse" data-parent="#faq" href="#collapseFive">
                    <h4 class="panel-title">
                        <a class="accordion-toggle collapsed" data-toggle="collapse">Are there any age restrictions?</a>
                    </h4>
                </div>
                <div id="collapseFive" class="panel-collapse collapse">
                    <div class="panel-body">
                        We've had sailing members from 8 years old to 85. Physical fitness is more important than age.
                        Sailing is one of those hobbies that suits all. You just need to pick the boat that suits you.
                    </div>
                </div>
            </div>

            <div class="cursor-pointer mb-3">
                <div class="shadow-sm panel-heading accordion-toggle collapsed secondary-color rounded p-3" data-toggle="collapse" data-parent="#faq" href="#collapseSix">
                    <h4 class="panel-title">
                        <a class="accordion-toggle collapsed" data-toggle="collapse">I'd like some training; What can you do for me?</a>
                    </h4>
                </div>
                <div id="collapseSix" class="panel-collapse collapse">
                    <div class="panel-body">
                    If you are a complete beginner, we have a number of RYA courses you can do as part of your membership.
                    If the schedule does not suite you, we can tailor it to your needs and put you with a buddy.
                    This is a person you team up with to guide you through your training.
                    He/She can help you arrange days of tuition to cover particular aspects or just advise you on how to improve your techniques.
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
    // for google map
    $this->inlineScript()->prependFile($this->basePath('js/map.driver.js'));
    $this->inlineScript()->prependFile($this->basePath('js/weather.colors.js'));
?>
